### ISSUE TITLE
Notification_Service_started doesn't run

### ISSUE THREAD

**Issue by BluFenix00** [MatthieuLemoine/electron-push-receiver#43] opened 2019-02-20 20:19 UTC
i just update my code from electron 1.8.8 to 3.0.5, when i update the NOTIFICATION_SERVICE_STARTED stop running

**Comment by MatthieuLemoine** [comment] 2019-02-21 12:42
I think it's a duplicate of https://github.com/MatthieuLemoine/push-receiver/issues/23.

Feel free to reopen if not

**Closed by MatthieuLemoine** 2019-02-21 12:42 UTC
