### ISSUE TITLE
A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by imd1whonocks** [MatthieuLemoine/electron-push-receiver#20] opened 2018-05-22 04:35 UTC
**Getting this error randomly. I am not able to identify source for this. To resolve this, I need to clear config.json file in app directory. Please help**
Uncaught Exception:
TypeError: Cannot read property 'value' of undefined
    at decrypt (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/utils/decrypt/index.js:10:5)
    at Client._onDataMessage (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/client.js:175:17)
    at Client._onMessage (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/client.js:164:12)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser._onGotMessageBytes (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:233:10)
    at Parser._waitForData (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:128:14)
    at Parser._onGotMessageSize (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:191:12)
    at Parser._onGotMessageTag (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:155:10)
    at Parser._waitForData (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:122:14)
    at Parser._onData (/home/shashank/office/office-chat-web/node_modules/push-receiver/src/parser.js:78:12)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)

**Comment by MatthieuLemoine** [comment] 2018-05-22 07:12
Duplicate of #18

**Closed by MatthieuLemoine** 2018-05-22 07:12 UTC
